baseURL = "https://andd.dk/hugotestsite/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cocoa"
publishdir = "docs"


[[menu.main]]
name = "Forside"
weight = -201
identifier = "forside"
url = "/"

[[menu.main]]
name = "Om"
weight = "-101"
identifier = "om"
url = "/om/"

[[menu.main]]
name = "Kontakt"
weight = "-101"
identifier = "kontakt"
url = "/kontakt/"

[[menu.main]]
name = "Blog"
weight = "-101"
identifier = "blog"
url = "/blog/"

[[menu.main]]
name = "Portfolio"
weight = "-101"
identifier = "portfolio"
url = "/portfolio/"

[params]
extracssfiles = [ "https://andd.dk/hugotestsite/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
